version: '2'
services:
  nodejs:
    build:
        context: .
        dockerfile: nodejs.Dockerfile
    ports:
        - "8088:80"
    networks: 
        - my-network
  my-locust:
    build:
        context: .
        dockerfile: my-locust.Dockerfile
    environment: 
        - LOCUST_MODE=standalone
        - TARGET_URL=http://nodejs
    ports:
        - "8089:8089"
    networks:
        - my-network
networks:
    my-network: